# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.24.1
# 

Name:       patchelf

# >> macros
# << macros

Summary:    A utility for patching ELF binaries
Version:    0.6
Release:    1
Group:      Development/Tools
License:    GPLv3
URL:        http://nixos.org/patchelf.html
Source0:    http://hydra.nixos.org/build/1524660/download/2/patchelf-0.6.tar.bz2
Source100:  patchelf.yaml

%description
PatchELF is a simple utility for modifing existing ELF executables and
libraries.  It can change the dynamic loader ("ELF interpreter") of
executables and change the RPATH of executables and libraries.



%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
autoreconf -v -f -i
# << build pre

%configure --disable-static
make %{?jobs:-j%jobs}

# >> build post
%if ! 0%{?qemu_user_space_build}
make check
%endif
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
strip $RPM_BUILD_ROOT/%{_prefix}/bin/* || true
# << install post


%files
%defattr(-,root,root,-)
%{_bindir}/patchelf
%{_datadir}/doc/patchelf/README
%{_datadir}/man/man1/patchelf.1.gz
# >> files
# << files
